### PR TITLE
Add more tests for the pcap/pcapng/dpkt/dns modules

### PR DESCRIPTION
**Pull request by crocogorical**
Reorganise tests in the pcapng/pcap/dpkt/dns modules, and add more.

Reusable test data is now accessible in the `TestData` class, rather than per test function.  

Contributing to #186

### CODE REVIEW

**Comment by brifordwylie** [comment]
@crocogorical wow... this is great. There's a lot of changes here... sorry just now looking at this. I'll try to review this soon. Perhaps @obormot can also take a pass :)

**Comment by crocogorical** [comment]
When issues #398 and #395 are resolved, there will be 100% coverage of `dns.py`.

**Comment by brifordwylie** [comment]
@crocogorical sorry for letting this bit-rot for so long. I'd really like to merge this work in. Do you mind resolving the two merge conflicts that happened in the meantime...  once those get resolved we merge this right away.

**Comment by brifordwylie** [comment]
@crocogorical closing this ticket, moved your code/PR to #502 .... I double pinky promise it will get merged in the next couple of days :)

**Pull request closed without merging**
