### PR TITLE
We now correctly parse IGMPv2 group TLV.

### PR DESCRIPTION
**Pull request by hexcap**
I have been using and making edits to DPKT 1.7 from the Google code page for a couple years. Recently I noticed DPKT now has a Github page, so I've contributing back my changes. This is a pull request for two commits.

The first fixes a bug in igmp.py and is relatively atomic.

The second could not be made any more atomic as supporting 802.1q/p and EDP required the modification of ethernet.py.

Thanks,
Andrew

### CODE REVIEW

**Comment by kbandla** [comment]
@hexcap i'm going to take a look at this PR over the next few days and merge it. Thanks!

**Comment by saylenty** [comment]
@kbandla before merging I think that we should delete his "merge" commit from the history and squash 1, 2, 3 commits? As a result we will have history like this: 
1. Feature commit 1
2. Feature commit 2
3. Fix spasing
4. Fix indentetion
It would be even better if:
1. Feature commit 1 (with all fixes)
2. Feature commit 2 (with all fixes)
This will help us to create clear development history.
What are your views?

**Comment by brifordwylie** [comment]
There are two tests that are failing, so lets clean those up. https://travis-ci.org/kbandla/dpkt/builds/81848108  On the squash issue, I'm not a fan of squash but that's just my own personal bias. After the two tests are cleanup up someone will have to cherry-pick https://github.com/kbandla/dpkt/commit/b8fe25c7b310954daca86df730e36eaa2d06fb19 for coveralls to pass.

**Comment by brifordwylie** [comment]
Lets not let PR languish too long.... @hexcap please cherry-pick b8fe25c for travis/coveralls to pass, and then @kbandla can merge this.

**Comment by brifordwylie** [comment]
@kbandla and @hexcap can we revisit this, there are a few tests failing specificially
- dpkt/ieee80211.py::test_80211_data FAILED
- dpkt/llc.py::test_llc FAILED

Lets fix those and have @kbandla merge this when he gets a chance.

**Comment by brifordwylie** [comment]
@hexcap why did you close this? We just need to fix a couple of small tests...

**Comment by brifordwylie** [comment]
Here's the link to the failing tests: https://travis-ci.org/kbandla/dpkt/jobs/81848110

**Comment by hexcap** [comment]
I'm picking this up after a long hiatus because I finally have some time to work on it. Sorry for taking so long on this. First off, smutt@github and hexcap@github are the same person, me, otherwise known as Andrew McConachie :) I just use hexcap@github specifically for work on hexcap. I was using smutt@github to work on another project that uses dpkt (middlebox-dane.org) but that project has quieted down and I have more time to resume work on hexcap (hexcap.org).

A lot has changed since I first wrote my code supporting 802.1q/p in dpkt. I started on my fork before dpkt was even in github. Now I think it makes sense to discard the changes in my branch WRT ethernet.py and llc.py in favor of what currently exists in kbandla@github. I would however like to merge a bugfix in igmp.py and support for Extreme Discovery Protocol(EDP) in edp.py, that are both only in my fork. Support for EDP will require an additional ethernet payload type defined in ethernet.py, but I don't believe any other changes to ethernet.py are necessary.

Given the above, I would like to close this PR and open two separate PRs. One for the bugfix in igmp.py and another to add support for EDP. I will stage these two changes in smutt@github. Once they are merged I will delete the dpkt fork in hexcap@github because there's really no reason to keep that code around anymore. Hexcap is very tightly coupled with dpkt and going forward I really don't want to maintain a separate fork of dpkt just for hexcap.

Before I do anything I wanted to post here and give the dpkt maintainers a chance to think about this and comment. What say ye? Good idea? Worst idea you've ever heard?

Also, and completely unrelated, python-dpkt is now in the OpenWRT/LEDE package repository as of a week ago and I am the maintainer.

**Comment by kbandla** [comment]
@hexcap : sounds good! You can close this PR and open the two PRs like you pointed.

**Comment by hexcap** [comment]
Just initiated PR #387.

**Comment by hexcap** [comment]
Just initiated PR #388

**Comment by brifordwylie** [comment]
Closing this per suggestion/discussion from @hexcap and @kbandla

**Pull request closed without merging**
