### PR TITLE
deprecated and duration decorators

### PR DESCRIPTION
**Pull request by Saylenty**
deprecated_method_decorator renamed as deprecated.
duration decorator - now it is available to measure execution time in pystones

### CODE REVIEW

**Comment by kbandla** [comment]
Reviewing..

**Comment by Saylenty** [comment]
Any update?

**Comment by brifordwylie** [comment]
@Saylenty Looks good to me, first time I've seen PyStones... I'm assuming it a way of getting performance measurement that decoupled from the particular machine. Since @kbandla is reviewing I'll let him do the merge.

**Comment by Saylenty** [comment]
@brifordwylie yes, PyStones - is a way to measure performance of the program, function in a platform independent way. If you are interested in some benchmark of the function you just "prefixed" function/method with duration decorator (specifying the optional argument how many times this should be called to measure execution time) and voila performance results are shown. Overall, it would be more correctly to announce them (results) rather then just seconds.

**Comment by brifordwylie** [comment]
Super nice, I'm going to start using that on other projects.

**Comment by Saylenty** [comment]
@brifordwylie you are welcome :-) Good to know that your are a useful person :-)

**Comment by brifordwylie** [comment]
I'm going to assume that @kbandla got super busy, I'm going to merge this and he can yell at me later :)

**Comment by kbandla** [comment]
:+1: looks good!

**Pull request merged**
