### PR TITLE
Fix #199: ImportError: No module named test.

### LINKED ISSUE #199: ImportError: No module named test
Some people using the dpkt-master have experienced this issue:
```
>>> import test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named test
```
This could occur because of many different reasons. We need to have a fallback when we fail to find pystone.

### PR DESCRIPTION
**Pull request by sunhao2014**
Since we never use the `duration` decorator in the project. Just simply remove the `duration` decorator and related test to solve the issue.

### CODE REVIEW

**Comment by kbandla** [comment]
Yeah, @saylenty was testing decorator performance early on. We can safely merge this pr

**Comment by saylenty** [comment]
If we or smb don't use this decorator, I think pr should be marged. :+1:

**Comment by kbandla** [comment]
You can also get rid of the other two import statements (timeit and sleep). Then merge.

**Comment by sunhao2014** [comment]
Sure, the two imports has been removed. Merging.

**Pull request merged**
