### PR TITLE
add new python versions to travis build

### PR DESCRIPTION
**Pull request by brifordwylie**
Shrug.. there might be a better way to do this, but you need to tell Travis CI how to map tox env to Python version. Again I haven't looked at this in a while so might be a better/easier way.

### CODE REVIEW

**Comment by brifordwylie** [comment]
Hmm... Travis Python 3.7 has an issue (https://github.com/travis-ci/travis-ci/issues/9815).... putting in the work around now...

**Comment by brifordwylie** [comment]
Ha... so now 3.7 works but 2.6 and pypy do not.... ;p
- https://travis-ci.org/kbandla/dpkt/builds/458129811

@obormot you're the most active contributor... what do you want to do here?
My suggestion:
- Remove 3.7 test for now (so... 2.6, 2.7, 3.5, 3.6, and pypy)
- I'll make a ticket for 3.7 support and look into it

**Comment by obormot** [comment]
interestingly 3.7 / tox worked fine in my local builds
thanks @brifordwylie !

**Comment by brifordwylie** [comment]
@obormot "interestingly 3.7 / tox worked fine in my local builds"  yep.. the code works fine with python 3.7.. the issue is the Travis CI machine installing running 3.7....

**Comment by brifordwylie** [comment]
Added ticket for Python 3.7 (https://github.com/kbandla/dpkt/issues/429). This is now building fine with 2.6, 2,7, 3.5, 3.6 and pypy. So going to merge this in and we can add 3.7 later with ticket above.

**Pull request merged**
