### PR TITLE
Made everything Python3 compatible.

### PR DESCRIPTION
**Pull request by jonathanslenders**
Hi all, this branch should make dpkt Python 3 compatible.
It should still run correctly on Python 2.

### CODE REVIEW

**Comment by kbandla** [comment]
@jonathanslenders did you use the `migrate_py3` branch as the basis for this?

**Comment by kylekeppler** [comment]
@kbandla, no this was not derived from the `migrate_py3` branch. I spent some time the last two days working on merging `jonathanslenders:python3-compatibility`, `migrate_py3` and `master` since the `migrate_py3` branch is so out of date. I have all tests passing on` py2.7` and `py3.5`.  I'll get this uploaded soon. I'd love for some more people to try it out and for it to eventually get pulled to master.

**Comment by kylekeppler** [comment]
Here is the PR [#307](https://github.com/kbandla/dpkt/pull/307).

**Comment by brifordwylie** [comment]
This PR turned into #307 which has been merged, so closing this.

**Pull request closed without merging**
